--- !ditz.rubyforge.org,2008-03-06/project 
name: sexy
version: "0.5"
components: 
- !ditz.rubyforge.org,2008-03-06/component 
  name: sexy
releases: 
- !ditz.rubyforge.org,2008-03-06/release 
  name: "0.1"
  status: :unreleased
  release_time: 
  log_events: 
  - - 2009-11-23 20:55:02.504104 Z
    - Nico Schottelius <nico@ikn.ethz.ch>
    - created
    - First public partly usable version
